
//Auth Types
export const SET_USER = "SET_USER"
export const USER_ERRORS = "USER_ERRORS"
export const CREATE_USER = "CREATE_USER"
export const FORGOT_PASSWORD = "FORGOT_PASSWORD"
export const RESET_PASSWORD = "RESET_PASSWORD"
export const SEND_OTP = "SEND_OTP"
export const VERIFY_OTP = "VERIFY_OTP"
export const ERRORS = "ERRORS"
export const SET_COUNTRY_INFO = "SET_COUNTRY_INFO"
export const LOGOUT = "LOGOUT"
export const SAVE_PROFILE = "SAVE_PROFILE"
export const GET_PROFILE = "GET_PROFILE"
export const GET_CUSTOMERUSER_PROFILE= "GET_CUSTOMERUSER_PROFILE"
export const GET_LAWYERUSER_PROFILE= "GET_LAWYERUSER_PROFILE"
//Admin Types
export const SET_ADMIN = "SET_ADMIN"
export const ADMINS_ERROR = "ADMINS_ERROR"
export const GET_PACKAGES="GET_PACKAGES"
export const GET_LAWFIRMUSER_PROFILE= "GET_LAWFIRMUSER_PROFILE"

//Blog Types
export const GET_POSTS = "GET_POSTS";
export const GET_POSTS_USING_SEARCH = "GET_POSTS_USING_SEARCH";
export const GET_SINGLE_POST = "GET_SINGLE_POST";
export const GET_USER_POSTS = "GET_USER_POSTS";
export const DELETE_POST = "DELETE_POST";
export const CREATE_POST = "CREATE_POST";
export const UPDATE_POST = "UPDATE_POST";
export const GET_COMMENTS = "GET_COMMENTS";
export const DELETE_COMMENT = "DELETE_COMMENTS";
export const POST_COMMENT = "DELETE_COMMENTS";

//Businesses Types
export const GET_BUSINESSES = "GET_BUSINESSES";
export const GET_BUSINESS_DETAIL = "GET_BUSINESS_DETAIL";
export const CLEAR_BUSINESSES_ITEMS = "CLEAR_BUSINESSES_ITEMS";
export const GET_BUSINESS_TYPES = "GET_BUSINESS_TYPES"

//Messaging Types
export const GET_CHATLIST = "GET_CHATLIST"
export const CREATE_CONVERSATION = "CREATE_CONVERSATION"
export const SEND_MESSAGE = "SEND_MESSAGE"
export const GET_MESSAGES = "GET_MESSAGES"

// Lawfirm Agency Types

export const GET_LAWFIRMS= "GET_LAWFIRMS"
export const GET_SINGLE_LAWFIRM= "GET_SINGLE_LAWFIRM"
export const CLEAR_LAWFIRMS= "CLEAR_LAWFIRMS"

// Lawfirm Agency Types

export const GET_LAWYERS= "GET_LAWYERS"
export const GET_SINGLE_LAWYER= "GET_SINGLE_LAWYER"
export const CLEAR_LAWYERS= "CLEAR_LAWYERS"

