export const lawCats =[
    "Administrative Law",
    "Auto Accident",
    "Aviation",
    "Banking & Finance",
    "Bankruptcy & Debt",
    "Body Corporation & Starta Law",
    "Business Law",
   "Charities Law",
    "Child Custody",
    "Child Support",
    "Civil Rights",
    "Commercial Real Estate",
    "Construction Law",
    "Consumer & Small Claims",
    "Criminal Defense Law",
    "Debt Settlement",
    "Defamation, Libel & Slander",
    "Divorce & Seperation",
    "Domestic Violence",
    "DUI and DWI",
    "Elder Law",
    "Employement Law",
    "Energy & Resources",
    "Family Law",
    "Frnachising Law",
    "Gaminf, Leisure & Hospitality",
    "Government Law",
    "Immigration Law",
    "Insurance Law",
    "Intellectual Property Law",
    "Landlord and Tenant",
    "Legal Malpractice",
    "Litigation & Dispute Resolution",
    "Long Term Disability",
    "Maritime",
    "Media & Entertainement Law",
    "Medical Law",
    "Mergers & Acquisitions",
    "Notary Public",
    "Patents",
    "Personal Injury Law",
    "Planning & Environment", 
    "Power Of Attorney",
    "Privacy Law",
    "Probate",
    "Product Liability",
    "Property Law",
    "Real Estate",
    "Restructuring & Insovency",
    "Securities",
    "Sex Crimes",
    "Sexual Harassment",
    "Sports Law",
    "Startup Law",
    "Tax Law",
    "Technology Law",
    "Traffic Law",
    "Veterans Disability",
    "Wills, Estate Planning & Probate",
    "Workers Compensation"


]

export const lawCatsModal = lawCats.reduce((acc,value,index)=>{
    return acc=[...acc,{value:value,id:index+1}]
    

},[])